/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/7aa986f6-d4cb-4ac7-80eb-8cc541a4a996

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSchedule pill1;
  CloudSchedule pill2;
  CloudSchedule pill3;
  bool triggerPill1;
  bool triggerPill2;
  bool triggerPill3;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#include <ESP32Servo.h>
#include <Time.h>
#include <NewPing.h>
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>

#include <Arduino.h>

#include <WiFi.h>
#include <WiFiMulti.h>

#include <HTTPClient.h>

#include <WiFiClientSecure.h>

const char* rootCACertificate = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIOXDCCDUSgAwIBAgIQC4qW7YghEegKnIaHXa2RujANBgkqhkiG9w0BAQsFADBG\n" \
"MQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExM\n" \
"QzETMBEGA1UEAxMKR1RTIENBIDFDMzAeFw0yNDAyMjYwODAzNThaFw0yNDA1MjAw\n" \
"ODAzNTdaMBcxFTATBgNVBAMMDCouZ29vZ2xlLmNvbTBZMBMGByqGSM49AgEGCCqG\n" \
"SM49AwEHA0IABDcjUHrrhpBkerx+V4G9nu+kN+XtZS3Bn67I82B090mbtY/EX4ob\n" \
"Bbuj/96VxVcREzi1vBiiOP2gDCcFlHSx++Wjggw+MIIMOjAOBgNVHQ8BAf8EBAMC\n" \
"B4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU\n" \
"uZ6msB8g5B2jp3fMRSgOyO0pmoMwHwYDVR0jBBgwFoAUinR/r4XN7pXNPZzQ4kYU\n" \
"83E1HScwagYIKwYBBQUHAQEEXjBcMCcGCCsGAQUFBzABhhtodHRwOi8vb2NzcC5w\n" \
"a2kuZ29vZy9ndHMxYzMwMQYIKwYBBQUHMAKGJWh0dHA6Ly9wa2kuZ29vZy9yZXBv\n" \
"L2NlcnRzL2d0czFjMy5kZXIwggnvBgNVHREEggnmMIIJ4oIMKi5nb29nbGUuY29t\n" \
"ghYqLmFwcGVuZ2luZS5nb29nbGUuY29tggkqLmJkbi5kZXaCFSoub3JpZ2luLXRl\n" \
"c3QuYmRuLmRldoISKi5jbG91ZC5nb29nbGUuY29tghgqLmNyb3dkc291cmNlLmdv\n" \
"b2dsZS5jb22CGCouZGF0YWNvbXB1dGUuZ29vZ2xlLmNvbYILKi5nb29nbGUuY2GC\n" \
"CyouZ29vZ2xlLmNsgg4qLmdvb2dsZS5jby5pboIOKi5nb29nbGUuY28uanCCDiou\n" \
"Z29vZ2xlLmNvLnVrgg8qLmdvb2dsZS5jb20uYXKCDyouZ29vZ2xlLmNvbS5hdYIP\n" \
"Ki5nb29nbGUuY29tLmJygg8qLmdvb2dsZS5jb20uY2+CDyouZ29vZ2xlLmNvbS5t\n" \
"eIIPKi5nb29nbGUuY29tLnRygg8qLmdvb2dsZS5jb20udm6CCyouZ29vZ2xlLmRl\n" \
"ggsqLmdvb2dsZS5lc4ILKi5nb29nbGUuZnKCCyouZ29vZ2xlLmh1ggsqLmdvb2ds\n" \
"ZS5pdIILKi5nb29nbGUubmyCCyouZ29vZ2xlLnBsggsqLmdvb2dsZS5wdIIPKi5n\n" \
"b29nbGVhcGlzLmNughEqLmdvb2dsZXZpZGVvLmNvbYIMKi5nc3RhdGljLmNughAq\n" \
"LmdzdGF0aWMtY24uY29tgg9nb29nbGVjbmFwcHMuY26CESouZ29vZ2xlY25hcHBz\n" \
"LmNughFnb29nbGVhcHBzLWNuLmNvbYITKi5nb29nbGVhcHBzLWNuLmNvbYIMZ2tl\n" \
"Y25hcHBzLmNugg4qLmdrZWNuYXBwcy5jboISZ29vZ2xlZG93bmxvYWRzLmNughQq\n" \
"Lmdvb2dsZWRvd25sb2Fkcy5jboIQcmVjYXB0Y2hhLm5ldC5jboISKi5yZWNhcHRj\n" \
"aGEubmV0LmNughByZWNhcHRjaGEtY24ubmV0ghIqLnJlY2FwdGNoYS1jbi5uZXSC\n" \
"C3dpZGV2aW5lLmNugg0qLndpZGV2aW5lLmNughFhbXBwcm9qZWN0Lm9yZy5jboIT\n" \
"Ki5hbXBwcm9qZWN0Lm9yZy5jboIRYW1wcHJvamVjdC5uZXQuY26CEyouYW1wcHJv\n" \
"amVjdC5uZXQuY26CF2dvb2dsZS1hbmFseXRpY3MtY24uY29tghkqLmdvb2dsZS1h\n" \
"bmFseXRpY3MtY24uY29tghdnb29nbGVhZHNlcnZpY2VzLWNuLmNvbYIZKi5nb29n\n" \
"bGVhZHNlcnZpY2VzLWNuLmNvbYIRZ29vZ2xldmFkcy1jbi5jb22CEyouZ29vZ2xl\n" \
"dmFkcy1jbi5jb22CEWdvb2dsZWFwaXMtY24uY29tghMqLmdvb2dsZWFwaXMtY24u\n" \
"Y29tghVnb29nbGVvcHRpbWl6ZS1jbi5jb22CFyouZ29vZ2xlb3B0aW1pemUtY24u\n" \
"Y29tghJkb3VibGVjbGljay1jbi5uZXSCFCouZG91YmxlY2xpY2stY24ubmV0ghgq\n" \
"LmZscy5kb3VibGVjbGljay1jbi5uZXSCFiouZy5kb3VibGVjbGljay1jbi5uZXSC\n" \
"DmRvdWJsZWNsaWNrLmNughAqLmRvdWJsZWNsaWNrLmNughQqLmZscy5kb3VibGVj\n" \
"bGljay5jboISKi5nLmRvdWJsZWNsaWNrLmNughFkYXJ0c2VhcmNoLWNuLm5ldIIT\n" \
"Ki5kYXJ0c2VhcmNoLWNuLm5ldIIdZ29vZ2xldHJhdmVsYWRzZXJ2aWNlcy1jbi5j\n" \
"b22CHyouZ29vZ2xldHJhdmVsYWRzZXJ2aWNlcy1jbi5jb22CGGdvb2dsZXRhZ3Nl\n" \
"cnZpY2VzLWNuLmNvbYIaKi5nb29nbGV0YWdzZXJ2aWNlcy1jbi5jb22CF2dvb2ds\n" \
"ZXRhZ21hbmFnZXItY24uY29tghkqLmdvb2dsZXRhZ21hbmFnZXItY24uY29tghhn\n" \
"b29nbGVzeW5kaWNhdGlvbi1jbi5jb22CGiouZ29vZ2xlc3luZGljYXRpb24tY24u\n" \
"Y29tgiQqLnNhZmVmcmFtZS5nb29nbGVzeW5kaWNhdGlvbi1jbi5jb22CFmFwcC1t\n" \
"ZWFzdXJlbWVudC1jbi5jb22CGCouYXBwLW1lYXN1cmVtZW50LWNuLmNvbYILZ3Z0\n" \
"MS1jbi5jb22CDSouZ3Z0MS1jbi5jb22CC2d2dDItY24uY29tgg0qLmd2dDItY24u\n" \
"Y29tggsybWRuLWNuLm5ldIINKi4ybWRuLWNuLm5ldIIUZ29vZ2xlZmxpZ2h0cy1j\n" \
"bi5uZXSCFiouZ29vZ2xlZmxpZ2h0cy1jbi5uZXSCDGFkbW9iLWNuLmNvbYIOKi5h\n" \
"ZG1vYi1jbi5jb22CFGdvb2dsZXNhbmRib3gtY24uY29tghYqLmdvb2dsZXNhbmRi\n" \
"b3gtY24uY29tgh4qLnNhZmVudXAuZ29vZ2xlc2FuZGJveC1jbi5jb22CDSouZ3N0\n" \
"YXRpYy5jb22CFCoubWV0cmljLmdzdGF0aWMuY29tggoqLmd2dDEuY29tghEqLmdj\n" \
"cGNkbi5ndnQxLmNvbYIKKi5ndnQyLmNvbYIOKi5nY3AuZ3Z0Mi5jb22CECoudXJs\n" \
"Lmdvb2dsZS5jb22CFioueW91dHViZS1ub2Nvb2tpZS5jb22CCyoueXRpbWcuY29t\n" \
"ggthbmRyb2lkLmNvbYINKi5hbmRyb2lkLmNvbYITKi5mbGFzaC5hbmRyb2lkLmNv\n" \
"bYIEZy5jboIGKi5nLmNuggRnLmNvggYqLmcuY2+CBmdvby5nbIIKd3d3Lmdvby5n\n" \
"bIIUZ29vZ2xlLWFuYWx5dGljcy5jb22CFiouZ29vZ2xlLWFuYWx5dGljcy5jb22C\n" \
"Cmdvb2dsZS5jb22CEmdvb2dsZWNvbW1lcmNlLmNvbYIUKi5nb29nbGVjb21tZXJj\n" \
"ZS5jb22CCGdncGh0LmNuggoqLmdncGh0LmNuggp1cmNoaW4uY29tggwqLnVyY2hp\n" \
"bi5jb22CCHlvdXR1LmJlggt5b3V0dWJlLmNvbYINKi55b3V0dWJlLmNvbYIUeW91\n" \
"dHViZWVkdWNhdGlvbi5jb22CFioueW91dHViZWVkdWNhdGlvbi5jb22CD3lvdXR1\n" \
"YmVraWRzLmNvbYIRKi55b3V0dWJla2lkcy5jb22CBXl0LmJlggcqLnl0LmJlghph\n" \
"bmRyb2lkLmNsaWVudHMuZ29vZ2xlLmNvbYIbZGV2ZWxvcGVyLmFuZHJvaWQuZ29v\n" \
"Z2xlLmNughxkZXZlbG9wZXJzLmFuZHJvaWQuZ29vZ2xlLmNughhzb3VyY2UuYW5k\n" \
"cm9pZC5nb29nbGUuY26CGmRldmVsb3Blci5jaHJvbWUuZ29vZ2xlLmNughh3ZWIu\n" \
"ZGV2ZWxvcGVycy5nb29nbGUuY24wIQYDVR0gBBowGDAIBgZngQwBAgEwDAYKKwYB\n" \
"BAHWeQIFAzA8BgNVHR8ENTAzMDGgL6AthitodHRwOi8vY3Jscy5wa2kuZ29vZy9n\n" \
"dHMxYzMvUXFGeGJpOU00OGMuY3JsMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHUA\n" \
"SLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMAAAGN5Kgj5wAABAMARjBE\n" \
"AiAl/DsuiWV2bzGEm3CjQlMn9caqhg/72OfO8s2Xdu2kdgIgIzYonvPVLpgbS074\n" \
"wIKggm26jnyfwjGZEmhfyeeyTi8AdgB2/4g/Crb7lVHCYcz1h7o0tKTNuyncaEIK\n" \
"n+ZnTFo6dAAAAY3kqCPuAAAEAwBHMEUCIHNEL+zc96PCpvfKZL4+ih/E/BSp+NDG\n" \
"yxmGZLhMWwnuAiEAsPAZwykqqNkOa6j0iThN7GKBW+SLKA19RxlQBGZaFTEwDQYJ\n" \
"KoZIhvcNAQELBQADggEBAIYOWDqpVHdInrypMTlDuY4w14CITqRWa+UgrjmRWOCK\n" \
"I5JE0Itv4h7+oc04+5g7Njm42NdRR4kPjfPtfvNUYvFxEdVtCf8yBTNTu+G782RR\n" \
"Xe6V2iIy6DawUjet8PgDBGVYnAp5cm/ldIJBschT0kPuRqIaG69bXhjNryKcLZTx\n" \
"n8pclPvAEPJRJ4RYnkiTqS2wu9NnCH4yKZj2Hcl714rlw+npdeQ5zWMSNV8R0nlu\n" \
"goWsaLbuxarMskN3JO/LfFO+VKB2uXJNcsGu6YymlSqy3z79BsXrl2yqDvuuMByt\n" \
"otFzZK8dElLYQERVOBeVfzHHgEsFkXRP3qcWKZRbryQ=\n" \
"-----END CERTIFICATE-----\n";


// String url = String(“/macros/s/”) + GScriptId + “/exec?”;

// Servo PINS and setup
#define MED_1 19 // ESP32 pin GPIO19 connected to servo motor
#define MED_2 18 // ESP32 pin GPIO18 connected to servo motor
#define MED_3 5  // ESP32 pin GPIO05 connected to servo motor

Servo servoMed1;
Servo servoMed2;
Servo servoMed3;

// I2C Display
#define i2c_Address 0x3c //initialize with the I2C addr 0x3C

#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels
#define OLED_RESET -1   //   QT-PY / XIAO
Adafruit_SH1106G display = Adafruit_SH1106G(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

// IR Obstacle
int inputPin = 36;

// Buzzer for Alarm
int buzzerPin = 2;
WiFiMulti WiFiMulti;
medname = "";
compnum = "";
request = "https://script.google.com/macros/s/AKfycbxD75rbn5gBMBx5AKK_wttlbJtXRxRUr4TYZ1fG0iIPd_ZuCIVgkMmnoQclq71v53hMSA/exec";
void setup() {

  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP("2GFelicidade", "MiraMaria");

  // wait for WiFi connection
  Serial.print("Waiting for WiFi to connect...");
  while ((WiFiMulti.run() != WL_CONNECTED)) {
    Serial.print(".");
  }
  Serial.println(" connected");
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  servoMed1.attach(MED_1);  // attaches the servo on ESP32 pin
  servoMed2.attach(MED_2);  // attaches the servo on ESP32 pin
  servoMed3.attach(MED_3);  // attaches the servo on ESP32 pin
  initializeAllServo();

  display.begin(i2c_Address, true); // Address 0x3C default

  display.display();
  delay(2000);

  // Clear the buffer.
  display.clearDisplay();

  // IR Pin
  pinMode(inputPin, INPUT);

  // Buzzer Pin
  pinMode(buzzerPin, OUTPUT);

  // Initialize Trigger
  triggerPill1 = LOW;
  triggerPill2 = LOW;
  triggerPill3 = LOW;
    //Initialize Wifi Connection
}

void loop() {
  WiFiClientSecure *client = new WiFiClientSecure;
  client->setInsecure();

  ArduinoCloud.update();

  // Your code here
  checkMedSchedule();

}

void initializeAllServo()
{
  servoMed1.write(0);
  delay(50);
  servoMed2.write(0);
  delay(50);
  servoMed3.write(0);
  delay(50);
}

// checking the schedule of each MedPill
// set the duration on the widget for 1 second
// each pill active, print in OLED (TBC)
void checkMedSchedule(void)
{
  HTTPClient http;
  if (pill1.isActive())
  {
    medname = "Clopidogrel";
    compnum = "1";
    if(client) {
    client -> setCACert(rootCACertificate);

    {
      // Add a scoping block for HTTPClient https to make sure it is destroyed before WiFiClientSecure *client is 
      HTTPClient https;
  
      Serial.print("[HTTPS] begin...\n");
      if (https.begin(*client, request + "?medicinename=" + medname + "&compartmentnumber=" + compnum)) {  // HTTPS
        Serial.print("[HTTPS] GET...\n");
        // start connection and send HTTP header
        int httpCode = https.GET();
  
        // httpCode will be negative on error
        if (httpCode > 0) {
          // HTTP header has been send and Server response header has been handled
          Serial.printf("[HTTPS] GET... code: %d\n", httpCode);
  
          // file found at server
          if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY) {
            String payload = https.getString();
            Serial.println(payload);
          }
        } else {
          Serial.printf("[HTTPS] GET... failed, error: %s\n", https.errorToString(httpCode).c_str());
        }
  
        https.end();
      } else {
        Serial.printf("[HTTPS] Unable to connect\n");
      }

      // End extra scoping block
    }
  
    delete client;
  } else {
    Serial.println("Unable to create client");
  }
    digitalWrite(buzzerPin, HIGH);

    triggerPill1 = HIGH; // Activate Trigger to send push notification and email

    display.display();
    display.clearDisplay();

    Schedule localPill1Schedule = pill1.getValue();

    display.setTextSize(1);
    display.setTextColor(SH110X_WHITE);
    display.setCursor(0, 30);
    // Display static text
    display.print("Clopidogrel");
    display.print(hour(localPill1Schedule.frm));
    display.print(":");
    display.print(minute(localPill1Schedule.frm));
    display.print(":");
    display.print(second(localPill1Schedule.frm));
    display.println("");
    display.display();

    Serial.print("It is time to take Clopidogrel now: ");
    Serial.print(hour(localPill1Schedule.frm));
    Serial.print(":");
    Serial.print(minute(localPill1Schedule.frm));
    Serial.print(":");
    Serial.print(second(localPill1Schedule.frm));
    Serial.println("");

   while((digitalRead(inputPin) == HIGH)) // lock the med if there is no hands
    {
      Serial.println("IR not triggered");
    }                                        // Set the Schedule Duration for 10mins
    Serial.println("IR Triggered hand detected");

    openMed1();

    delay(5000);

    closeMed1();
    display.setCursor(0, 40);
    // Display static text
    display.print("Clopidogrel taken ");
  }

  if (pill2.isActive())
  {
    medname = "Rosuvastatin";
    compnum = "2";
    if(client) {
    client -> setCACert(rootCACertificate);

    {
      // Add a scoping block for HTTPClient https to make sure it is destroyed before WiFiClientSecure *client is 
      HTTPClient https;
  
      Serial.print("[HTTPS] begin...\n");
      if (https.begin(*client, request + "?medicinename=" + medname + "&compartmentnumber=" + compnum)) {  // HTTPS
        Serial.print("[HTTPS] GET...\n");
        // start connection and send HTTP header
        int httpCode = https.GET();
  
        // httpCode will be negative on error
        if (httpCode > 0) {
          // HTTP header has been send and Server response header has been handled
          Serial.printf("[HTTPS] GET... code: %d\n", httpCode);
  
          // file found at server
          if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY) {
            String payload = https.getString();
            Serial.println(payload);
          }
        } else {
          Serial.printf("[HTTPS] GET... failed, error: %s\n", https.errorToString(httpCode).c_str());
        }
  
        https.end();
      } else {
        Serial.printf("[HTTPS] Unable to connect\n");
      }

      // End extra scoping block
    }
  
    delete client;
  } else {
    Serial.println("Unable to create client");
  }
    digitalWrite(buzzerPin, HIGH);

    triggerPill2 = HIGH; // Activate Trigger to send push notification and email

    display.display();
    display.clearDisplay();

    Schedule localPill2Schedule = pill2.getValue();
    display.setTextSize(1);
    display.setTextColor(SH110X_WHITE);
    display.setCursor(0, 30);
    // Display static text
    display.print("Rosuvastatin");
    display.print(hour(localPill2Schedule.frm));
    display.print(":");
    display.print(minute(localPill2Schedule.frm));
    display.print(":");
    display.print(second(localPill2Schedule.frm));
    display.println("");
    display.display();
    Serial.print("It is time to take Rosuvastatin now: ");
    Serial.print(hour(localPill2Schedule.frm));
    Serial.print(":");
    Serial.print(minute(localPill2Schedule.frm));
    Serial.print(":");
    Serial.print(second(localPill2Schedule.frm));
    Serial.println("");

   while((digitalRead(inputPin) == HIGH)) // lock the med if there is no hands
    {
      Serial.println("IR not triggered");
    }                                        // Set the Schedule Duration for 10mins
    Serial.println("IR Triggered hand detected");

    openMed2();
    delay(5000);
    closeMed2();
    display.setCursor(0, 40);
    // Display static text
    display.print("Rosuvastatin taken ");

  }

  if (pill3.isActive())
  {
    medname = "Ranolazine";
    compnum = "3";
    if(client) {
    client -> setCACert(rootCACertificate);

    {
      // Add a scoping block for HTTPClient https to make sure it is destroyed before WiFiClientSecure *client is 
      HTTPClient https;
  
      Serial.print("[HTTPS] begin...\n");
      if (https.begin(*client, request + "?medicinename=" + medname + "&compartmentnumber=" + compnum)) {  // HTTPS
        Serial.print("[HTTPS] GET...\n");
        // start connection and send HTTP header
        int httpCode = https.GET();
  
        // httpCode will be negative on error
        if (httpCode > 0) {
          // HTTP header has been send and Server response header has been handled
          Serial.printf("[HTTPS] GET... code: %d\n", httpCode);
  
          // file found at server
          if (httpCode == HTTP_CODE_OK || httpCode == HTTP_CODE_MOVED_PERMANENTLY) {
            String payload = https.getString();
            Serial.println(payload);
          }
        } else {
          Serial.printf("[HTTPS] GET... failed, error: %s\n", https.errorToString(httpCode).c_str());
        }
  
        https.end();
      } else {
        Serial.printf("[HTTPS] Unable to connect\n");
      }

      // End extra scoping block
    }
  
    delete client;
  } else {
    Serial.println("Unable to create client");
  }
    digitalWrite(buzzerPin, HIGH);

    triggerPill3 = HIGH; // Activate Trigger to send push notification and email

    display.display();
    display.clearDisplay();

    Schedule localPill3Schedule = pill3.getValue();
    display.setTextSize(1);
    display.setTextColor(SH110X_WHITE);
    display.setCursor(0, 30);
    // Display static text
    display.print("Ranolazine");
    display.print(hour(localPill3Schedule.frm));
    display.print(":");
    display.print(minute(localPill3Schedule.frm));
    display.print(":");
    display.print(second(localPill3Schedule.frm));
    display.println("");
    display.display();
    Serial.print("It is time to take Ranolazine now: ");
    Serial.print(hour(localPill3Schedule.frm));
    Serial.print(":");
    Serial.print(minute(localPill3Schedule.frm));
    Serial.print(":");
    Serial.print(second(localPill3Schedule.frm));
    Serial.println("");

  while((digitalRead(inputPin) == HIGH)) // lock the med if there is no hands
    {
      Serial.println("IR not triggered");
    }                                        // Set the Schedule Duration for 10mins
    Serial.println("IR Triggered hand detected");

    openMed3();
    delay(5000);
    closeMed3();
    display.setCursor(0, 40);
    // Display static text
    display.print("Ranolazine taken");


  }
}

/*
  Since Scheduler is READ_WRITE variable, onSchedulerChange() is
  executed every time a new value is received from IoT Cloud.
*/

void onSchedulerChange()  {
  // Add your code here to act upon Scheduler change


}


/*
  Since Pill1 is READ_WRITE variable, onPill1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPill1Change()  {
  // Add your code here to act upon Pill1 change
  Schedule localPill1ScheduleChange = pill1.getValue();
  display.setTextSize(1);
  display.setTextColor(SH110X_WHITE);
  display.setCursor(0, 0);
  // Display static text
  display.println("Pill 1 Schedule : ");
  display.print(hour(localPill1ScheduleChange.frm));
  display.print(":");
  display.print(minute(localPill1ScheduleChange.frm));
  display.print(":");
  display.print(second(localPill1ScheduleChange.frm));
  display.println("");
  display.display();

  Serial.print("Pill 1 Schedule starts: ");
  Serial.print(hour(localPill1ScheduleChange.frm));
  Serial.print(":");
  Serial.print(minute(localPill1ScheduleChange.frm));
  Serial.print(":");
  Serial.print(second(localPill1ScheduleChange.frm));
  Serial.println("");

}

/*
  Since Pill2 is READ_WRITE variable, onPill2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPill2Change()  {
  // Add your code here to act upon Pill2 change
  Schedule localPill2ScheduleChange = pill2.getValue();
  display.setTextSize(1);
  display.setTextColor(SH110X_WHITE);
  display.setCursor(0, 25);
  // Display static text
  display.println("Pill 2 Schedule : ");
  display.print(hour(localPill2ScheduleChange.frm));
  display.print(":");
  display.print(minute(localPill2ScheduleChange.frm));
  display.print(":");
  display.print(second(localPill2ScheduleChange.frm));
  display.println("");
  display.display();

  Serial.print("Pill 2 Schedule starts: ");
  Serial.print(hour(localPill2ScheduleChange.frm));
  Serial.print(":");
  Serial.print(minute(localPill2ScheduleChange.frm));
  Serial.print(":");
  Serial.print(second(localPill2ScheduleChange.frm));
  Serial.println("");
}


/*
  Since Pill3 is READ_WRITE variable, onPill3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onPill3Change()  {
  // Add your code here to act upon Pill3 change
  Schedule localPill3ScheduleChange = pill3.getValue();
  display.setTextSize(1);
  display.setTextColor(SH110X_WHITE);
  display.setCursor(0, 45);
  // Display static text
  display.println("Pill 3 Schedule : ");
  display.print(hour(localPill3ScheduleChange.frm));
  display.print(":");
  display.print(minute(localPill3ScheduleChange.frm));
  display.print(":");
  display.print(second(localPill3ScheduleChange.frm));
  display.println("");
  display.display();

  Serial.print("Pill 3 Schedule starts: ");
  Serial.print(hour(localPill3ScheduleChange.frm));
  Serial.print(":");
  Serial.print(minute(localPill3ScheduleChange.frm));
  Serial.print(":");
  Serial.print(second(localPill3ScheduleChange.frm));
  Serial.println("");
}

void openMed1(void)
{
  digitalWrite(buzzerPin, LOW);
  // rotates from 0 degrees to 180 degrees
  for (int pos = 0; pos <= 105; pos += 1) {
    // in steps of 1 degree
    servoMed1.write(pos);
    delay(15); // waits 15ms to reach the position
  }
  delay(1000);
}

void closeMed1(void)
{
  // rotates from 180 degrees to 0 degrees
  for (int pos = 105; pos >= 0; pos -= 1) {
    servoMed1.write(pos);
    delay(15); // waits 15ms to reach the position
  }
}

void openMed2(void)
{
  digitalWrite(buzzerPin, LOW);
  // rotates from 0 degrees to 180 degrees
  for (int pos = 0; pos <= 105; pos += 1) {
    // in steps of 1 degree
    servoMed2.write(pos);
    delay(15); // waits 15ms to reach the position
  }
  delay(1000);
}

void closeMed2(void)
{
  // rotates from 180 degrees to 0 degrees
  for (int pos = 105; pos >= 0; pos -= 1) {
    servoMed2.write(pos);
    delay(15); // waits 15ms to reach the position
  }
}

void openMed3(void)
{
  digitalWrite(buzzerPin, LOW);
  // rotates from 0 degrees to 180 degrees
  for (int pos = 0; pos <= 105; pos += 1) {
    // in steps of 1 degree
    servoMed3.write(pos);
    delay(15); // waits 15ms to reach the position
  }
  delay(1000);
}

void closeMed3(void)
{
  // rotates from 180 degrees to 0 degrees
  for (int pos = 105; pos >= 0; pos -= 1) {
    servoMed3.write(pos);
    delay(15); // waits 15ms to reach the position
  }
}

/*
  Since TriggerPill1 is READ_WRITE variable, onTriggerPill1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onTriggerPill1Change()  {
  // Add your code here to act upon TriggerPill1 change
}

/*
  Since TriggerPill2 is READ_WRITE variable, onTriggerPill2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onTriggerPill2Change()  {
  // Add your code here to act upon TriggerPill2 change
}

/*
  Since TriggerPill3 is READ_WRITE variable, onTriggerPill3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onTriggerPill3Change()  {
  // Add your code here to act upon TriggerPill3 change
}
